-- This file is automatically generated using `scripts/make_language_table.py`.

module Data.LanguageNames where
import Data.LanguageNamesData
import Data.ByteString (ByteString)
import qualified Data.Map as Map
import qualified Data.ByteString.Char8 as Char8
import qualified Data.ByteString.UTF8 as UTF8

unknownCode :: ByteString -> ByteString
unknownCode name =
  Char8.concat [
    UTF8.fromString "und-x-",
    Char8.intercalate (UTF8.fromString "-") $ Char8.split ' ' name]
    

lookupLanguage :: ByteString -> ByteString -> ByteString
lookupLanguage lang name =
  Map.findWithDefault (unknownCode name) (lang, name) languageMap

entryTuple :: String -> ((ByteString, ByteString), ByteString)
entryTuple line =
  let entry = Char8.split ',' (UTF8.fromString line)
      lang  = entry !! 0
      name  = entry !! 1
      code  = entry !! 2
  in ((lang, name), code)

languageMap :: Map.Map (ByteString, ByteString) ByteString
languageMap = Map.fromList (map entryTuple (lines languageData))
