"""
A Python script that uses data from `langcodes` to generate a simple
Haskell lookup table of language names.
"""
import langcodes

table_languages = ['en', 'de']


def main():
    print("-- This file is automatically generated using `scripts/make_language_table.py` .")
    print()
    print("lookupLanguage :: String -> String -> String")
    for namelang in table_languages:
        used_names = set()
        names = langcodes.DB.query("select subtag, name from language_name where language=? order by name, entry_order", namelang)
        for code, name in names:
            if name not in used_names:
                used_names.add(name)
                print('lookupLanguage "%s" "%s" = "%s"' % (namelang, name, code))
    print('lookupLanguage _ _ = "und"')


if __name__ == '__main__':
    main()
