"""
A Python script that uses data from `langcodes` to generate a simple
Haskell lookup table of language names.
"""
import langcodes

table_languages = ['en', 'de']

header = """
{-# LANGUAGE OverloadedStrings #-}
-- This file is automatically generated using `scripts/make_language_table.py`.

module Data.LanguageNames where
import qualified Data.Map as Map
import Data.ByteString (ByteString)

lookupLanguage :: ByteString -> ByteString -> ByteString
lookupLanguage lang name = Map.findWithDefault name (lang, name) languageNames

languageNames = Map.fromList [
""".strip()

def main():
    print(header)
    for namelang in table_languages:
        used_names = set()
        names = langcodes.DB.query("select subtag, name from language_name where language=? order by name, entry_order", namelang)
        for code, name in names:
            if len(code) == 2 and name not in used_names:
                used_names.add(name)
                print('  (("%s","%s"),"%s"),' % (namelang, name, code))
    # fake entry to finish the list
    print('  (("",""),"und")]')


if __name__ == '__main__':
    main()
